// Generated by gencpp from file rostls/EchoRequest.msg
// DO NOT EDIT!


#ifndef ROSTLS_MESSAGE_ECHOREQUEST_H
#define ROSTLS_MESSAGE_ECHOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rostls
{
template <class ContainerAllocator>
struct EchoRequest_
{
  typedef EchoRequest_<ContainerAllocator> Type;

  EchoRequest_()
    : call()  {
    }
  EchoRequest_(const ContainerAllocator& _alloc)
    : call(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _call_type;
  _call_type call;





  typedef boost::shared_ptr< ::rostls::EchoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rostls::EchoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EchoRequest_

typedef ::rostls::EchoRequest_<std::allocator<void> > EchoRequest;

typedef boost::shared_ptr< ::rostls::EchoRequest > EchoRequestPtr;
typedef boost::shared_ptr< ::rostls::EchoRequest const> EchoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rostls::EchoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rostls::EchoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rostls

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'rostls': ['/home/vagrant/rostls_ws/src/rostls/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rostls::EchoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rostls::EchoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rostls::EchoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rostls::EchoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostls::EchoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostls::EchoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rostls::EchoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3215900da2c21797ec453ce12acd7b3";
  }

  static const char* value(const ::rostls::EchoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3215900da2c2179ULL;
  static const uint64_t static_value2 = 0x7ec453ce12acd7b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rostls::EchoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rostls/EchoRequest";
  }

  static const char* value(const ::rostls::EchoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rostls::EchoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string call\n"
;
  }

  static const char* value(const ::rostls::EchoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rostls::EchoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.call);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EchoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rostls::EchoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rostls::EchoRequest_<ContainerAllocator>& v)
  {
    s << indent << "call: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.call);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSTLS_MESSAGE_ECHOREQUEST_H
