// Generated by gencpp from file rostls/Greeting.msg
// DO NOT EDIT!


#ifndef ROSTLS_MESSAGE_GREETING_H
#define ROSTLS_MESSAGE_GREETING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rostls
{
template <class ContainerAllocator>
struct Greeting_
{
  typedef Greeting_<ContainerAllocator> Type;

  Greeting_()
    : greeting()  {
    }
  Greeting_(const ContainerAllocator& _alloc)
    : greeting(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _greeting_type;
  _greeting_type greeting;





  typedef boost::shared_ptr< ::rostls::Greeting_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rostls::Greeting_<ContainerAllocator> const> ConstPtr;

}; // struct Greeting_

typedef ::rostls::Greeting_<std::allocator<void> > Greeting;

typedef boost::shared_ptr< ::rostls::Greeting > GreetingPtr;
typedef boost::shared_ptr< ::rostls::Greeting const> GreetingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rostls::Greeting_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rostls::Greeting_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rostls

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'rostls': ['/home/vagrant/rostls_ws/src/rostls/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rostls::Greeting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rostls::Greeting_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rostls::Greeting_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rostls::Greeting_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostls::Greeting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostls::Greeting_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rostls::Greeting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af3498ba158bcdd555fe81847eb6e16d";
  }

  static const char* value(const ::rostls::Greeting_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf3498ba158bcdd5ULL;
  static const uint64_t static_value2 = 0x55fe81847eb6e16dULL;
};

template<class ContainerAllocator>
struct DataType< ::rostls::Greeting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rostls/Greeting";
  }

  static const char* value(const ::rostls::Greeting_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rostls::Greeting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string greeting\n"
;
  }

  static const char* value(const ::rostls::Greeting_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rostls::Greeting_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.greeting);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Greeting_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rostls::Greeting_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rostls::Greeting_<ContainerAllocator>& v)
  {
    s << indent << "greeting: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.greeting);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSTLS_MESSAGE_GREETING_H
